#!/usr/bin/python
#coding:utf-8

from Class import TvList
from Class import ValueList
from Class import ListValueList


from type import shaanxi
from type import letv
from type import itv
from type import tianwei
from type import qq
from type import qqgq

CCTV1=TvList()
CCTV1.SetName("CCTV1")
CCTV1.TypeAdd(tianwei,"TWSX0004200211100000")
CCTV2=TvList()
CCTV2.SetName("CCTV2")
CCTV2.TypeAdd(letv,"cctv2")
CCTV3=TvList()
CCTV3.SetName("CCTV3")
CCTV3.TypeAdd(letv,"cctv3")
CCTV4=TvList()
CCTV4.SetName("CCTV4")
CCTV4.TypeAdd(letv,"cctv4")
CCTV5=TvList()
CCTV5.SetName("CCTV5")
CCTV5.TypeAdd(itv,"cctv5")
CCTV6=TvList()
CCTV6.SetName("CCTV6")
CCTV6.TypeAdd(letv,"cctv6")
CCTV7=TvList()
CCTV7.SetName("CCTV7")
CCTV7.TypeAdd(letv,"cctv7")
CCTV8=TvList()
CCTV8.SetName("CCTV8")
CCTV8.TypeAdd(letv,"cctv8")
CCTV9=TvList()
CCTV9.SetName("CCTV9")
CCTV9.TypeAdd(letv,"cctv9")
CCTV10=TvList()
CCTV10.SetName("CCTV10")
CCTV10.TypeAdd(letv,"cctv10")
CCTV11=TvList()
CCTV11.SetName("CCTV11")
CCTV11.TypeAdd(letv,"cctv11")
CCTV12=TvList()
CCTV12.SetName("CCTV12")
CCTV12.TypeAdd(letv,"cctv12")

ws_hb=TvList()
ws_hb.SetName("湖北卫视")
ws_hb.TypeAdd(qq,"1128831868")
ws_tj=TvList()
ws_tj.SetName("天津卫视")
ws_tj.TypeAdd(qq,"830075195")
ws_dn=TvList()
ws_dn.SetName("东南卫视")
ws_dn.TypeAdd(qq,"1000637964")
ws_ah=TvList()
ws_ah.SetName("安徽卫视")
ws_ah.TypeAdd(qq,"623043810")
ws_df=TvList()
ws_df.SetName("东方卫视")
ws_df.TypeAdd(qq,"3661744838")
ws_df.TypeAdd(qqgq,"3900155972")
ws_gd=TvList()
ws_gd.SetName("广东卫视")
ws_gd.TypeAdd(qq,"2084914015")
ws_gd.TypeAdd(qqgq,"857894899")
ws_zj=TvList()
ws_zj.SetName("浙江卫视")
ws_zj.TypeAdd(qq,"2907109968")
ws_zj.TypeAdd(qqgq,"1975434150")
ws_gz=TvList()
ws_gz.SetName("贵州卫视")
ws_gz.TypeAdd(qq,"3051487004")
ws_sz=TvList()
ws_sz.SetName("深圳卫视")
ws_sz.TypeAdd(qq,"2309309351")
ws_sz.TypeAdd(qqgq,"2220552576")
ws_sc=TvList()
ws_sc.SetName("四川卫视")
ws_sc.TypeAdd(qq,"2453801339")
ws_nm=TvList()
ws_nm.SetName("内蒙古卫视")
ws_nm.TypeAdd(qq,"2342060367")
ws_nx=TvList()
ws_nx.SetName("宁夏卫视")
ws_nx.TypeAdd(qq,"3778086045")
ws_gs=TvList()
ws_gs.SetName("甘肃卫视")
ws_gs.TypeAdd(qq,"3444760127")
ws_cq=TvList()
ws_cq.SetName("重庆卫视")
ws_cq.TypeAdd(qq,"2905421066")
ws_gx=TvList()
ws_gx.SetName("广西卫视")
ws_gx.TypeAdd(qq,"974433428")
ws_henan=TvList()
ws_henan.SetName("河南卫视")
ws_henan.TypeAdd(qq,"4172356212")
ws_yn=TvList()
ws_yn.SetName("云南卫视")
ws_yn.TypeAdd(qq,"708402866")
ws_shaanxi=TvList()
ws_shaanxi.SetName("陕西卫视")
ws_shaanxi.TypeAdd(qq,"2739752321")
ws_shaanxi.TypeAdd(shaanxi,"8")
ws_sd=TvList()
ws_sd.SetName("山东卫视")
ws_sd.TypeAdd(qq,"3660187036")
ws_qh=TvList()
ws_qh.SetName("青海卫视")
ws_qh.TypeAdd(qq,"877636586")
ws_ln=TvList()
ws_ln.SetName("辽宁卫视")
ws_ln.TypeAdd(qq,"3006271240")

shaanxi_1=TvList()
shaanxi_1.SetName("陕西新闻资讯")
shaanxi_1.TypeAdd(shaanxi,"1")
shaanxi_2=TvList()
shaanxi_2.SetName("陕西都市生活")
shaanxi_2.TypeAdd(shaanxi,"2")
shaanxi_3=TvList()
shaanxi_3.SetName("陕西经济")
shaanxi_3.TypeAdd(shaanxi,"3")
shaanxi_5=TvList()
shaanxi_5.SetName("陕西公共")
shaanxi_5.TypeAdd(shaanxi,"5")
shaanxi_6=TvList()
shaanxi_6.SetName("陕西乐家购物")
shaanxi_6.TypeAdd(shaanxi,"6")
shaanxi_7=TvList()
shaanxi_7.SetName("陕西体育")
shaanxi_7.TypeAdd(shaanxi,"7")
shaanxi_9=TvList()
shaanxi_9.SetName("陕西农林卫视")
shaanxi_9.TypeAdd(shaanxi,"9")


List_CCTV=ValueList()
List_CCTV.SetThisName("央视")
List_CCTV.Add(CCTV1)
List_CCTV.Add(CCTV2)
List_CCTV.Add(CCTV3)
List_CCTV.Add(CCTV4)
List_CCTV.Add(CCTV5)
List_CCTV.Add(CCTV6)
List_CCTV.Add(CCTV7)
List_CCTV.Add(CCTV8)
List_CCTV.Add(CCTV9)
List_CCTV.Add(CCTV10)
List_CCTV.Add(CCTV11)
List_CCTV.Add(CCTV12)

List_WS=ValueList()
List_WS.SetThisName("地方卫视")
List_WS.Add(ws_hb)
List_WS.Add(ws_tj)
List_WS.Add(ws_dn)
List_WS.Add(ws_ah)
List_WS.Add(ws_df)
List_WS.Add(ws_gd)
List_WS.Add(ws_zj)
List_WS.Add(ws_gz)
List_WS.Add(ws_sz)
List_WS.Add(ws_sc)
List_WS.Add(ws_nm)
List_WS.Add(ws_nx)
List_WS.Add(ws_gs)
List_WS.Add(ws_cq)
List_WS.Add(ws_gx)
List_WS.Add(ws_henan)
List_WS.Add(ws_yn)
List_WS.Add(ws_shaanxi)
List_WS.Add(ws_sd)
List_WS.Add(ws_qh)
List_WS.Add(ws_ln)

List_shaanxi=ValueList()
List_shaanxi.SetThisName("陕西")
List_shaanxi.Add(shaanxi_1)
List_shaanxi.Add(shaanxi_2)
List_shaanxi.Add(shaanxi_3)
List_shaanxi.Add(shaanxi_5)
List_shaanxi.Add(shaanxi_6)
List_shaanxi.Add(shaanxi_7)
List_shaanxi.Add(ws_shaanxi)
List_shaanxi.Add(shaanxi_9)


Tv=ListValueList()
Tv.Add(List_CCTV)
Tv.Add(List_WS)
Tv.Add(List_shaanxi)

